[build]
builder = "docker-compose"
dockercompose_path = "docker-compose.yml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on-failure"
